name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Describe what you'd like EchOS to do.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What are you trying to do that EchOS currently can't do well?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Agent / AI behaviour
        - Plugin system
        - Telegram interface
        - Web UI
        - TUI
        - Search
        - Storage / Sync
        - Scheduler / Background jobs
        - Setup / Installation
        - Security
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'd be willing to open a PR for this
