import { readFileSync, readdirSync } from 'fs';
import { join } from 'path';

const dataDir = 'data/db/vectors/documents.lance/data';
let files;

try {
  files = readdirSync(dataDir);
} catch {
  console.error('Cannot find LanceDB data directory:', dataDir);
  console.error('Have you run pnpm reconcile yet?');
  process.exit(1);
}

if (files.length === 0) {
  console.log('No data files found — table is empty');
  process.exit(0);
}

console.log(`Found ${files.length} data file(s):`, files);

// Lance files store vectors as raw float32. Each vector is 1536 * 4 = 6144 bytes.
// We scan the binary data looking for non-zero float32 values to confirm real embeddings.
const buf = readFileSync(join(dataDir, files[0]));
console.log(`File size: ${buf.length} bytes`);

let nonZeroCount = 0;
const samples = [];

// Scan the entire file for non-zero finite float32 values
for (let i = 0; i < buf.length - 3; i += 4) {
  const val = buf.readFloatLE(i);
  if (val !== 0 && !isNaN(val) && isFinite(val) && Math.abs(val) < 10) {
    // The <10 filter excludes large integer-like values from metadata/offsets
    nonZeroCount++;
    if (samples.length < 8) samples.push(val.toFixed(6));
  }
}

console.log(`\nNon-zero float32 values (plausible embedding range): ${nonZeroCount}`);
console.log(`Sample values: [${samples.join(', ')}]`);

if (nonZeroCount > 50) {
  console.log('\n✅ REAL VECTORS confirmed — data file contains non-zero float values');
  console.log('   Semantic search should work correctly.');
} else {
  console.log('\n❌ ZERO VECTORS — all values are 0');
  console.log('   Embeddings were NOT generated by OpenAI.');
  console.log('   Check that OPENAI_API_KEY is set in .env and run:');
  console.log('   rm -rf data/db && pnpm reconcile');
}
