#!/usr/bin/env -S pnpm tsx

/**
 * EchOS Web Setup Server
 *
 * Zero-dependency (uses only Node.js built-ins) server that serves a
 * browser-based setup wizard. Writes .env and creates data directories.
 *
 * Usage:
 *   pnpm setup              # starts server + opens browser
 *   pnpm setup --port 3456  # custom port
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as http from 'node:http';
import { randomBytes } from 'node:crypto';
import { createConnection } from 'node:net';
import { exec } from 'node:child_process';

const args = process.argv.slice(2);
const PORT = (() => {
  const portArgIndex = args.indexOf('--port');
  if (portArgIndex === -1) return 3456;

  const rawPort = args[portArgIndex + 1];
  if (!rawPort || rawPort.startsWith('-')) {
    console.error('Error: --port flag requires a numeric value.\nUsage: pnpm setup --port 3456');
    process.exit(1);
  }

  const parsedPort = parseInt(rawPort, 10);
  if (!Number.isInteger(parsedPort) || parsedPort <= 0 || parsedPort > 65535) {
    console.error(`Error: Invalid port "${rawPort}". Port must be an integer between 1 and 65535.`);
    process.exit(1);
  }

  return parsedPort;
})();

// ─── Helpers ──────────────────────────────────────────────────────────────────

function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const raw = trimmed.slice(eq + 1).trim();
    const value = raw.replace(/^(['"])(.*)\1$/, '$2');
    result[key] = value;
  }
  return result;
}

function sanitizeEnvValue(value: string): string {
  // Strip newlines/carriage returns to prevent env injection
  return value.replace(/[\r\n]/g, '');
}

function stateToEnv(state: Record<string, unknown>): string {
  const s = (k: string): string => sanitizeEnvValue(String(state[k] ?? ''));
  const lines: string[] = [
    '# EchOS Configuration — generated by echos setup',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# ── Required ────────────────────────────────────────────────────────────────',
    `ANTHROPIC_API_KEY=${s('anthropicApiKey')}`,
    `ALLOWED_USER_IDS=${s('allowedUserIds')}`,
    '',
    '# ── OpenAI (optional, for embeddings and Whisper) ───────────────────────────',
    s('openaiApiKey') ? `OPENAI_API_KEY=${s('openaiApiKey')}` : '# OPENAI_API_KEY=',
    '',
    '# ── Interfaces ───────────────────────────────────────────────────────────────',
    `ENABLE_TELEGRAM=${s('enableTelegram')}`,
    `ENABLE_WEB=${s('enableWeb')}`,
    `WEB_PORT=${s('webPort') || '3000'}`,
    s('webApiKey') ? `WEB_API_KEY=${s('webApiKey')}` : '# WEB_API_KEY=',
    '',
    '# ── Telegram (required when ENABLE_TELEGRAM=true) ───────────────────────────',
    s('telegramBotToken') ? `TELEGRAM_BOT_TOKEN=${s('telegramBotToken')}` : '# TELEGRAM_BOT_TOKEN=',
    '',
    '# ── Storage ──────────────────────────────────────────────────────────────────',
    `KNOWLEDGE_DIR=${s('knowledgeDir') || './data/knowledge'}`,
    `DB_PATH=${s('dbPath') || './data/db'}`,
    `SESSION_DIR=${s('sessionDir') || './data/sessions'}`,
    '',
    '# ── Redis (required) ─────────────────────────────────────────────────────────',
    `REDIS_URL=${s('redisUrl') || 'redis://localhost:6379'}`,
    s('digestSchedule') ? `DIGEST_SCHEDULE=${s('digestSchedule')}` : '# DIGEST_SCHEDULE=',
    s('reminderCheckSchedule') ? `REMINDER_CHECK_SCHEDULE=${s('reminderCheckSchedule')}` : '# REMINDER_CHECK_SCHEDULE=',
    '',
    '# ── Models ───────────────────────────────────────────────────────────────────',
    `DEFAULT_MODEL=${s('defaultModel') || 'claude-haiku-4-5-20251001'}`,
    `EMBEDDING_MODEL=${s('embeddingModel') || 'text-embedding-3-small'}`,
    '',
    '# ── Webshare Proxy (optional, for YouTube on cloud IPs) ─────────────────────',
    s('webshareProxyUsername') ? `WEBSHARE_PROXY_USERNAME=${s('webshareProxyUsername')}` : '# WEBSHARE_PROXY_USERNAME=',
    s('webshareProxyPassword') ? `WEBSHARE_PROXY_PASSWORD=${s('webshareProxyPassword')}` : '# WEBSHARE_PROXY_PASSWORD=',
    '',
  ];
  return lines.join('\n');
}

function readBody(req: http.IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks).toString()));
    req.on('error', reject);
  });
}

function json(res: http.ServerResponse, data: unknown, status = 200): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

// ─── Validation handlers ──────────────────────────────────────────────────────

async function validateAnthropic(body: { key: string }): Promise<{ valid: boolean; error?: string }> {
  if (!body.key?.startsWith('sk-ant-')) {
    return { valid: false, error: 'Key should start with sk-ant-' };
  }
  try {
    const resp = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      signal: AbortSignal.timeout(10000),
      headers: {
        'x-api-key': body.key,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1,
        messages: [{ role: 'user', content: 'Hi' }],
      }),
    });
    if (resp.status === 401) return { valid: false, error: 'API key rejected (401)' };
    if (resp.status === 400 || resp.ok) return { valid: true };
    return { valid: false, error: `Unexpected status ${resp.status}` };
  } catch (err: unknown) {
    return { valid: false, error: `Network error: ${err instanceof Error ? err.message : String(err)}` };
  }
}

async function validateOpenai(body: { key: string }): Promise<{ valid: boolean; error?: string }> {
  try {
    const resp = await fetch('https://api.openai.com/v1/models', {
      signal: AbortSignal.timeout(10000),
      headers: { Authorization: `Bearer ${body.key}` },
    });
    if (resp.status === 401) return { valid: false, error: 'API key rejected (401)' };
    if (resp.ok) return { valid: true };
    return { valid: false, error: `Unexpected status ${resp.status}` };
  } catch (err: unknown) {
    return { valid: false, error: `Network error: ${err instanceof Error ? err.message : String(err)}` };
  }
}

async function validateTelegram(body: { token: string }): Promise<{ valid: boolean; botName?: string; error?: string }> {
  try {
    const resp = await fetch(`https://api.telegram.org/bot${body.token}/getMe`, {
      signal: AbortSignal.timeout(10000),
    });
    const data = (await resp.json()) as { ok: boolean; result?: { username?: string } };
    if (data.ok) return { valid: true, botName: data.result?.username };
    return { valid: false, error: 'Bot token rejected by Telegram' };
  } catch (err: unknown) {
    return { valid: false, error: `Network error: ${err instanceof Error ? err.message : String(err)}` };
  }
}

function validateRedis(body: { url: string }): Promise<{ valid: boolean; error?: string }> {
  return new Promise((resolve) => {
    try {
      const parsed = new URL(body.url);
      const port = parseInt(parsed.port || '6379', 10);
      const host = parsed.hostname || 'localhost';
      const conn = createConnection({ host, port });
      conn.setTimeout(5000);
      conn.on('connect', () => { conn.destroy(); resolve({ valid: true }); });
      conn.on('error', (err) => resolve({ valid: false, error: err.message }));
      conn.on('timeout', () => { conn.destroy(); resolve({ valid: false, error: 'Connection timed out' }); });
    } catch (err: unknown) {
      resolve({ valid: false, error: `Invalid URL: ${err instanceof Error ? err.message : String(err)}` });
    }
  });
}

function writeConfig(state: Record<string, unknown>): { success: boolean; error?: string } {
  try {
    const envPath = path.resolve('.env');

    // Backup existing .env
    if (fs.existsSync(envPath)) {
      const backupPath = `${envPath}.backup.${Date.now()}`;
      fs.copyFileSync(envPath, backupPath);
    }

    const content = stateToEnv(state);
    fs.writeFileSync(envPath, content, { encoding: 'utf8', mode: 0o600 });
    fs.chmodSync(envPath, 0o600);

    // Create data directories
    const dirs = [
      String(state['knowledgeDir'] || './data/knowledge'),
      String(state['dbPath'] || './data/db'),
      String(state['sessionDir'] || './data/sessions'),
    ];
    for (const dir of dirs) {
      const resolved = path.resolve(dir);
      if (!fs.existsSync(resolved)) {
        fs.mkdirSync(resolved, { recursive: true });
      }
    }

    return { success: true };
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : String(err) };
  }
}

// ─── HTTP server ──────────────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url || '/', `http://localhost:${PORT}`);

  // Only allow localhost — strict match to prevent DNS rebinding (e.g. localhost.evil.com)
  const host = req.headers.host || '';
  if (!/^(localhost|127\.0\.0\.1)(:\d+)?$/.test(host)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }

  try {
    // Routes
    if (req.method === 'GET' && (url.pathname === '/' || url.pathname === '/setup')) {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(getSetupHtml());
      return;
    }

    if (req.method === 'GET' && url.pathname === '/api/setup/existing') {
      const envPath = path.resolve('.env');
      if (!fs.existsSync(envPath)) {
        json(res, { exists: false, config: {} });
        return;
      }
      const content = fs.readFileSync(envPath, 'utf8');
      const parsed = parseEnvFile(content);
      const masked: Record<string, string> = {};
      for (const [k, v] of Object.entries(parsed)) {
        if (k.includes('KEY') || k.includes('TOKEN') || k.includes('PASSWORD')) {
          masked[k] = v ? `${v.slice(0, 6)}...${v.slice(-4)}` : '';
        } else {
          masked[k] = v;
        }
      }
      json(res, { exists: true, config: masked });
      return;
    }

    if (req.method === 'POST') {
      const body = JSON.parse(await readBody(req));

      if (url.pathname === '/api/setup/validate-anthropic') {
        json(res, await validateAnthropic(body));
        return;
      }
      if (url.pathname === '/api/setup/validate-openai') {
        json(res, await validateOpenai(body));
        return;
      }
      if (url.pathname === '/api/setup/validate-telegram') {
        json(res, await validateTelegram(body));
        return;
      }
      if (url.pathname === '/api/setup/validate-redis') {
        json(res, await validateRedis(body));
        return;
      }
      if (url.pathname === '/api/setup/generate-key') {
        json(res, { key: randomBytes(32).toString('hex') });
        return;
      }
      if (url.pathname === '/api/setup/write-config') {
        json(res, writeConfig(body));
        return;
      }
    }

    res.writeHead(404);
    res.end('Not found');
  } catch (err: unknown) {
    console.error('Request error:', err);
    json(res, { error: 'Internal server error' }, 500);
  }
});

// ─── Setup HTML ───────────────────────────────────────────────────────────────

function getSetupHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EchOS Setup</title>
  <style>
    :root {
      --bg: #0a0a0a; --surface: #141414; --border: #2a2a2a;
      --text: #e0e0e0; --text-dim: #888;
      --accent: #06b6d4; --accent-hover: #22d3ee;
      --success: #22c55e; --warning: #eab308; --error: #ef4444;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
      background: var(--bg); color: var(--text);
      min-height: 100vh; display: flex; justify-content: center; padding: 2rem 1rem;
    }
    .container { width: 100%; max-width: 640px; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; color: var(--accent); }
    .subtitle { color: var(--text-dim); font-size: 0.875rem; margin-bottom: 2rem; }
    .step { display: none; animation: fadeIn 0.2s ease; }
    .step.active { display: block; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    .step-header { font-size: 1.125rem; font-weight: 600; margin-bottom: 0.5rem; display: flex; align-items: center; gap: 0.5rem; }
    .step-number { background: var(--accent); color: var(--bg); width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.75rem; font-weight: 700; }
    .step-desc { color: var(--text-dim); font-size: 0.8rem; margin-bottom: 1.5rem; }
    .step-desc a { color: var(--accent); }
    .field { margin-bottom: 1.25rem; }
    label { display: block; font-size: 0.8rem; font-weight: 500; margin-bottom: 0.375rem; }
    .label-hint { color: var(--text-dim); font-weight: 400; }
    input[type="text"], input[type="password"], input[type="number"] {
      width: 100%; padding: 0.625rem 0.75rem; background: var(--surface);
      border: 1px solid var(--border); border-radius: 6px; color: var(--text);
      font-size: 0.875rem; font-family: monospace; outline: none; transition: border-color 0.15s;
    }
    input:focus { border-color: var(--accent); }
    input::placeholder { color: #555; }
    .toggle-row {
      display: flex; align-items: center; justify-content: space-between;
      padding: 0.75rem; background: var(--surface); border: 1px solid var(--border);
      border-radius: 6px; margin-bottom: 1rem; cursor: pointer;
    }
    .toggle-row:hover { border-color: var(--accent); }
    .toggle-label { font-size: 0.875rem; }
    .toggle-hint { font-size: 0.75rem; color: var(--text-dim); }
    .toggle {
      position: relative; width: 42px; height: 24px; background: var(--border);
      border-radius: 12px; transition: background 0.2s; cursor: pointer; flex-shrink: 0;
    }
    .toggle.on { background: var(--accent); }
    .toggle::after {
      content: ''; position: absolute; top: 2px; left: 2px; width: 20px; height: 20px;
      background: white; border-radius: 50%; transition: transform 0.2s;
    }
    .toggle.on::after { transform: translateX(18px); }
    .validation { font-size: 0.75rem; margin-top: 0.375rem; min-height: 1.25rem; }
    .validation.success { color: var(--success); }
    .validation.error { color: var(--error); }
    .validation.loading { color: var(--text-dim); }
    .nav { display: flex; justify-content: space-between; margin-top: 2rem; padding-top: 1.5rem; border-top: 1px solid var(--border); }
    button { padding: 0.625rem 1.5rem; border-radius: 6px; font-size: 0.875rem; font-weight: 500; cursor: pointer; border: none; transition: all 0.15s; }
    .btn-primary { background: var(--accent); color: var(--bg); }
    .btn-primary:hover { background: var(--accent-hover); }
    .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
    .btn-secondary { background: transparent; color: var(--text-dim); border: 1px solid var(--border); }
    .btn-secondary:hover { border-color: var(--text-dim); color: var(--text); }
    .btn-validate { padding: 0.375rem 0.75rem; font-size: 0.75rem; background: var(--surface); color: var(--text-dim); border: 1px solid var(--border); border-radius: 4px; cursor: pointer; margin-top: 0.375rem; }
    .btn-validate:hover { border-color: var(--accent); color: var(--accent); }
    .progress { display: flex; gap: 0.5rem; margin-bottom: 2rem; }
    .progress-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--border); transition: background 0.2s; }
    .progress-dot.active { background: var(--accent); }
    .progress-dot.done { background: var(--success); }
    .summary-table { width: 100%; font-size: 0.8rem; margin-bottom: 1.5rem; border-collapse: collapse; }
    .summary-table tr { border-bottom: 1px solid var(--border); }
    .summary-table td { padding: 0.5rem 0; vertical-align: top; }
    .summary-table td:first-child { color: var(--text-dim); width: 140px; white-space: nowrap; }
    .summary-table td:last-child { font-family: monospace; word-break: break-all; }
    .masked { color: var(--text-dim); }
    .badge { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 4px; font-size: 0.7rem; font-weight: 600; }
    .badge-on { background: rgba(6,182,212,0.15); color: var(--accent); }
    .badge-off { background: rgba(136,136,136,0.15); color: var(--text-dim); }
    .success-screen { text-align: center; padding: 3rem 0; }
    .success-screen h2 { color: var(--success); font-size: 1.25rem; margin-bottom: 1rem; }
    .success-screen code { display: block; background: var(--surface); padding: 1rem; border-radius: 6px; margin: 0.5rem 0; font-family: monospace; font-size: 0.875rem; color: var(--accent); }
    .collapsible-header { cursor: pointer; user-select: none; display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0; color: var(--text-dim); font-size: 0.8rem; }
    .collapsible-header:hover { color: var(--text); }
    .collapsible-content { display: none; margin-top: 0.5rem; }
    .collapsible-content.open { display: block; }
    .arrow { transition: transform 0.2s; display: inline-block; }
    .arrow.open { transform: rotate(90deg); }
  </style>
</head>
<body>
  <div class="container">
    <h1>EchOS Setup</h1>
    <p class="subtitle">Configure your personal knowledge management system</p>
    <div class="progress" id="progress"></div>

    <!-- Step 1: API Keys -->
    <div class="step active" id="step-1">
      <div class="step-header"><span class="step-number">1</span> API Keys</div>
      <p class="step-desc">Connect to AI providers. Anthropic is required; OpenAI is optional (embeddings + Whisper transcription).</p>
      <div class="field">
        <label>Anthropic API Key <span class="label-hint">(required, starts with sk-ant-)</span></label>
        <input type="password" id="anthropicApiKey" placeholder="sk-ant-..." autocomplete="off">
        <button class="btn-validate" onclick="validateKey('anthropic')">Test key</button>
        <div class="validation" id="anthropic-status"></div>
      </div>
      <div class="field">
        <label>OpenAI API Key <span class="label-hint">(optional)</span></label>
        <input type="password" id="openaiApiKey" placeholder="sk-..." autocomplete="off">
        <button class="btn-validate" onclick="validateKey('openai')">Test key</button>
        <div class="validation" id="openai-status"></div>
      </div>
    </div>

    <!-- Step 2: Telegram -->
    <div class="step" id="step-2">
      <div class="step-header"><span class="step-number">2</span> Telegram Bot</div>
      <p class="step-desc">Set up your Telegram bot for messaging. Create one via <a href="https://t.me/BotFather" target="_blank">@BotFather</a>.</p>
      <div class="toggle-row" onclick="toggle('enableTelegram')">
        <div><div class="toggle-label">Enable Telegram</div><div class="toggle-hint">Recommended primary interface</div></div>
        <div class="toggle on" id="toggle-enableTelegram"></div>
      </div>
      <div id="telegram-fields">
        <div class="field">
          <label>Bot Token <span class="label-hint">(from @BotFather)</span></label>
          <input type="password" id="telegramBotToken" placeholder="123456789:ABCdef..." autocomplete="off">
          <button class="btn-validate" onclick="validateKey('telegram')">Test token</button>
          <div class="validation" id="telegram-status"></div>
        </div>
      </div>
      <div class="field">
        <label>Allowed User IDs <span class="label-hint">(required, comma-separated)</span></label>
        <input type="text" id="allowedUserIds" placeholder="123456789,987654321">
        <div class="validation" id="userid-hint" style="color:var(--text-dim)">Required for access control. Get your ID from <a href="https://t.me/userinfobot" target="_blank" style="color:var(--accent)">@userinfobot</a></div>
      </div>
    </div>

    <!-- Step 3: Features -->
    <div class="step" id="step-3">
      <div class="step-header"><span class="step-number">3</span> Features</div>
      <p class="step-desc">Enable additional interfaces and background features.</p>
      <div class="toggle-row" onclick="toggle('enableWeb')">
        <div><div class="toggle-label">Web UI</div><div class="toggle-hint">REST API + web interface (experimental)</div></div>
        <div class="toggle" id="toggle-enableWeb"></div>
      </div>
      <div id="web-fields" style="display:none">
        <div class="field"><label>Web Port</label><input type="number" id="webPort" value="3000"></div>
      </div>
      <div class="field">
        <label>Redis URL <span class="label-hint">(required — background scheduler)</span></label>
        <input type="text" id="redisUrl" value="redis://localhost:6379">
        <button class="btn-validate" onclick="validateKey('redis')">Test connection</button>
        <div class="validation" id="redis-status"></div>
      </div>
      <div class="collapsible-header" onclick="toggleCollapsible('advanced')">
        <span class="arrow" id="arrow-advanced">&#9654;</span> Advanced options
      </div>
      <div class="collapsible-content" id="collapsible-advanced">
        <div class="field"><label>Webshare Proxy Username <span class="label-hint">(optional, for YouTube on VPS)</span></label><input type="text" id="webshareProxyUsername"></div>
        <div class="field"><label>Webshare Proxy Password</label><input type="password" id="webshareProxyPassword"></div>
      </div>
    </div>

    <!-- Step 4: Summary -->
    <div class="step" id="step-4">
      <div class="step-header"><span class="step-number">4</span> Review & Confirm</div>
      <p class="step-desc">Review your configuration before writing to .env</p>
      <table class="summary-table" id="summary-table"></table>
    </div>

    <!-- Step 5: Success -->
    <div class="step" id="step-5">
      <div class="success-screen">
        <h2>Setup Complete</h2>
        <p style="color:var(--text-dim);margin-bottom:1.5rem">Your .env file has been written and data directories created.</p>
        <p style="font-size:0.875rem;margin-bottom:0.5rem">Start EchOS:</p>
        <code>pnpm start</code>
        <p style="font-size:0.875rem;margin-top:1.5rem;margin-bottom:0.5rem">Or use the CLI:</p>
        <code>pnpm echos</code>
        <p style="color:var(--text-dim);font-size:0.75rem;margin-top:2rem">You can close this tab now.</p>
      </div>
    </div>

    <div class="nav" id="nav">
      <button class="btn-secondary" id="btn-back" onclick="prevStep()" style="visibility:hidden">Back</button>
      <button class="btn-primary" id="btn-next" onclick="nextStep()">Next</button>
    </div>
  </div>

  <script>
    const TOTAL_STEPS = 4;
    let currentStep = 1;
    const toggles = { enableTelegram: true, enableWeb: false };

    function renderProgress() {
      const el = document.getElementById('progress');
      el.innerHTML = '';
      for (let i = 1; i <= TOTAL_STEPS; i++) {
        const dot = document.createElement('div');
        dot.className = 'progress-dot' + (i === currentStep ? ' active' : '') + (i < currentStep ? ' done' : '');
        el.appendChild(dot);
      }
    }

    function showStep(n) {
      currentStep = n;
      document.querySelectorAll('.step').forEach(s => s.classList.remove('active'));
      const step = document.getElementById('step-' + n);
      if (step) step.classList.add('active');
      const nav = document.getElementById('nav');
      if (n >= 5) { nav.style.display = 'none'; return; }
      nav.style.display = 'flex';
      document.getElementById('btn-back').style.visibility = n === 1 ? 'hidden' : 'visible';
      const btnNext = document.getElementById('btn-next');
      btnNext.textContent = n === TOTAL_STEPS ? 'Write .env & Finish' : 'Next';
      btnNext.disabled = false;
      if (n === TOTAL_STEPS) renderSummary();
      renderProgress();
    }

    function nextStep() {
      if (currentStep === 1) {
        const key = document.getElementById('anthropicApiKey').value.trim();
        if (!key) { showV('anthropic-status', 'error', 'Anthropic API key is required'); return; }
        if (!key.startsWith('sk-ant-')) { showV('anthropic-status', 'error', 'Key should start with sk-ant-'); return; }
      }
      if (currentStep === 2) {
        if (toggles.enableTelegram) {
          const token = document.getElementById('telegramBotToken').value.trim();
          if (!token) { showV('telegram-status', 'error', 'Bot token is required when Telegram is enabled'); return; }
        }
        const ids = document.getElementById('allowedUserIds').value.trim();
        if (!ids) { showV('userid-hint', 'error', 'At least one user ID is required (used for access control)'); return; }
        const idParts = ids.split(',').map(function (p) { return p.trim(); }).filter(function (p) { return p.length > 0; });
        if (!idParts.length) {
          showV('userid-hint', 'error', 'Please enter at least one numeric user ID (comma-separated).');
          return;
        }
        var invalidId = idParts.find(function (p) { return !/^[1-9]\d*$/.test(p); });
        if (invalidId) {
          showV('userid-hint', 'error', 'Allowed user IDs must be comma-separated positive integers (e.g. 12345,67890).');
          return;
        }
      }
      if (currentStep === TOTAL_STEPS) { writeConfig(); return; }
      showStep(currentStep + 1);
    }

    function prevStep() { if (currentStep > 1) showStep(currentStep - 1); }

    function toggle(name) {
      toggles[name] = !toggles[name];
      document.getElementById('toggle-' + name).classList.toggle('on', toggles[name]);
      const fields = { enableTelegram: 'telegram-fields', enableWeb: 'web-fields' };
      if (fields[name]) document.getElementById(fields[name]).style.display = toggles[name] ? '' : 'none';
    }

    function toggleCollapsible(name) {
      document.getElementById('collapsible-' + name).classList.toggle('open');
      document.getElementById('arrow-' + name).classList.toggle('open');
    }

    function showV(id, type, msg) {
      const el = document.getElementById(id);
      el.className = 'validation ' + type;
      el.textContent = msg;
    }

    function maskKey(k) { return (!k || k.length < 10) ? '(not set)' : k.slice(0, 6) + '...' + k.slice(-4); }

    async function validateKey(type) {
      const endpoints = {
        anthropic: ['/api/setup/validate-anthropic', () => ({ key: document.getElementById('anthropicApiKey').value.trim() })],
        openai: ['/api/setup/validate-openai', () => ({ key: document.getElementById('openaiApiKey').value.trim() })],
        telegram: ['/api/setup/validate-telegram', () => ({ token: document.getElementById('telegramBotToken').value.trim() })],
        redis: ['/api/setup/validate-redis', () => ({ url: document.getElementById('redisUrl').value.trim() })],
      };
      const [url, getBody] = endpoints[type];
      const statusId = type + '-status';
      showV(statusId, 'loading', 'Validating...');
      try {
        const r = await fetch(url, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(getBody()) }).then(r => r.json());
        const msg = r.valid ? (r.botName ? 'Connected as @' + r.botName : type === 'redis' ? 'Redis reachable' : 'Key is valid') : r.error;
        showV(statusId, r.valid ? 'success' : 'error', msg);
      } catch (e) { showV(statusId, 'error', 'Request failed'); }
    }

    function getState() {
      return {
        anthropicApiKey: document.getElementById('anthropicApiKey').value.trim(),
        openaiApiKey: document.getElementById('openaiApiKey').value.trim(),
        allowedUserIds: document.getElementById('allowedUserIds').value.trim(),
        enableTelegram: toggles.enableTelegram,
        telegramBotToken: document.getElementById('telegramBotToken').value.trim(),
        enableWeb: toggles.enableWeb,
        webPort: parseInt(document.getElementById('webPort').value) || 3000,
        webApiKey: '',
        redisUrl: document.getElementById('redisUrl').value.trim() || 'redis://localhost:6379',
        knowledgeDir: './data/knowledge', dbPath: './data/db', sessionDir: './data/sessions',
        defaultModel: 'claude-haiku-4-5-20251001', embeddingModel: 'text-embedding-3-small',
        webshareProxyUsername: document.getElementById('webshareProxyUsername').value.trim(),
        webshareProxyPassword: document.getElementById('webshareProxyPassword').value.trim(),
      };
    }

    function renderSummary() {
      const s = getState();
      const rows = [
        ['Anthropic Key', '<span class="masked">' + maskKey(s.anthropicApiKey) + '</span>'],
        ['OpenAI Key', s.openaiApiKey ? '<span class="masked">' + maskKey(s.openaiApiKey) + '</span>' : '<span class="masked">(not set)</span>'],
        ['Telegram', s.enableTelegram ? '<span class="badge badge-on">enabled</span>' : '<span class="badge badge-off">disabled</span>'],
        ['Allowed Users', s.allowedUserIds || '(none)'],
        ['Web UI', s.enableWeb ? '<span class="badge badge-on">:' + s.webPort + '</span>' : '<span class="badge badge-off">disabled</span>'],
        ['Redis', '<span class="badge badge-on">enabled</span> ' + s.redisUrl],
      ];
      document.getElementById('summary-table').innerHTML = rows.map(([k,v]) => '<tr><td>' + k + '</td><td>' + v + '</td></tr>').join('');
    }

    async function writeConfig() {
      const state = getState();
      if (state.enableWeb && !state.webApiKey) {
        const r = await fetch('/api/setup/generate-key', { method: 'POST' }).then(r => r.json());
        state.webApiKey = r.key;
      }
      const btn = document.getElementById('btn-next');
      btn.disabled = true; btn.textContent = 'Writing...';
      try {
        const r = await fetch('/api/setup/write-config', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(state) }).then(r => r.json());
        if (r.success) showStep(5);
        else { btn.disabled = false; btn.textContent = 'Write .env & Finish'; alert('Error: ' + r.error); }
      } catch (e) { btn.disabled = false; btn.textContent = 'Write .env & Finish'; alert('Failed: ' + (e instanceof Error ? e.message : String(e))); }
    }

    renderProgress();
  </script>
</body>
</html>`;
}

// ─── Start server ─────────────────────────────────────────────────────────────

server.listen(PORT, '127.0.0.1', () => {
  const url = `http://127.0.0.1:${PORT}/setup`;
  console.log(`\n  \x1b[1m\x1b[36mEchOS Setup\x1b[0m is running at: \x1b[36m${url}\x1b[0m\n`);

  // Try to open browser
  const openCmd = process.platform === 'darwin'
    ? `open "${url}"`
    : process.platform === 'linux'
      ? `xdg-open "${url}" 2>/dev/null || sensible-browser "${url}" 2>/dev/null`
      : '';

  if (openCmd) {
    exec(openCmd, (err) => {
      if (err) {
        console.log(`  Open \x1b[36m${url}\x1b[0m in your browser to continue.\n`);
      }
    });
  }
});
